### Create a new feature flag
POST http://localhost:9000/flags
Content-Type: application/json

{
  "name": "new-checkout-experience",
  "description": "This is a new feature"
}

### Get a feature flag
GET http://localhost:9000/flags/new-checkout-experience

### Toggle a feature flag
PUT http://localhost:9000/flags/new-checkout-experience
Content-Type: application/json

{
  "enabled": true
}

### Add a percentage rollout rule
POST http://localhost:9000/flags/new-checkout-experience/rules
Content-Type: application/json

{
  "type": "PERCENTAGE_ROLLOUT",
  "percentage": 50
}

### Evaluate a feature flag
GET http://localhost:9000/evaluate?flagName=new-checkout-experience&workspaceId=some-workspace

###
GET http://localhost:9000/api/v1/dynamic-checkout?workspaceId=some-workspace

###
GET http://localhost:9000/api/v1/dynamic-checkout?workspaceId=some-workspace-3