version: '3.8'
services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: feature_flags
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"
