version: '3.8'
services:
  mysql:
    image: mysql:8.0
    container_name: feature_flag_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: feature_flag_db
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: feature_flags
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  redis:
    image: redis:6
    ports:
      - "6379:6379"
