version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: feature_flag_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: feature_flag_db
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d  # 초기화 SQL 파일 (선택사항)
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --default-authentication-plugin=mysql_native_password
    networks:
      - feature_flag_network

volumes:
  mysql_data:
    driver: local

networks:
  feature_flag_network:
    driver: bridge