version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: feature_flag_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: feature_flag_db
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci